### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yoshi314** [ehlers/unyaffs#7] opened 2018-03-19 10:07 UTC
```
unyaffs.c:(.text+0x14d5): undefined reference to `minor'
unyaffs.c:(.text+0x14e6): undefined reference to `major'
unyaffs.c:(.text+0x1543): undefined reference to `minor'
unyaffs.c:(.text+0x1554): undefined reference to `major'
collect2: error: ld returned 1 exit status
```

adding 
```
#include <sys/sysmacros.h>
```

resolves the problem.

**Comment by ehlers** [comment] 2018-03-27 13:53
What OS, OS version, C compiler, compiler version are you using?

Unconditionally including \<sys/sysmacros.h\> won't work, since this include file is not available on all systems. So I need to develop some conditional inclusion. My current idea is to use that:

```
#ifdef __GLIBC__
#include <sys/sysmacros.h>
#endif
```

Can you please test, if that compiles on your system?

**Comment by yoshi314** [comment] 2018-03-29 09:06
I'll give it a shot.

I am using current gentoo on amd64, gcc-7.3

**Comment by yoshi314** [comment] 2018-03-29 09:07
The patch does not work. I altered it to 

```
#if defined(__linux__)
```

and now it does, but not sure if that is correct.

**Comment by ehlers** [comment] 2018-03-29 09:28
I can't reproduce your issue on gentoo. I only get some ugly warnings, but the build process works. I just pushed a fix for the warnings.

As I have no way to further analyze that, I close it.

**Closed by ehlers** 2018-03-29 09:28 UTC

**Comment by ehlers** [comment] 2018-03-29 10:30
Made some tests on various platforms and you're right, only using `#ifdef __GLIBC__` is not enough. I've combined both ideas, now I'm using `#if defined(__linux__) || defined(__GLIBC__)`, that should work better.

Thanks a lot for your input.
